volumes:
  pg_data:
  mail_data:

services:
  db:
    image: docker.io/postgres:18
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db

  prometheus:
    image: docker.io/prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: docker.io/grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yml

  mail:
    image: docker.io/axllent/mailpit
    ports:
      - 127.0.0.1:8025:8025 # Web UI
      - 127.0.0.1:1025:1025 # SMTP Server
    volumes:
      - mail_data:/data
